version: 2
jobs:
  build:
    docker:
      - image: openfl/openfl.org-build:0.0.8
    steps:
      - checkout
      - run:
          name: Install
          command: _scripts/install.sh
      - run:
          name: Build
          command: _scripts/build.sh
      - deploy:
          name: Deploy (if on master)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              _scripts/deploy.sh
            else
              echo "Not on master (skipping step)"
            fi
